### ISSUE TITLE
Connecting and configuring wm8731 proto board

### ISSUE THREAD

**Issue by smutax** [sinneb/esp32-hvcc#3]
Hi there. Loving this project. Hope it is still being maintained. Can you advise please how one needs to modify the schematic in order to connect and utilize wm8731 based breakout board(mikroe-506)?
https://www.mikroe.com/audio-codec-proto-board
All the best and stay safe.

**Comment by sinneb** [comment]
Hi Smutax. Thank you for your interest and sorry for this very late reply. I've started working on this project again. For now I'm planning a simplification of the project with only PCM5102's to get underway. The WM8731 will be a future upgrade.

**Comment by smutax** [comment]
Hi @sinneb! Glad you are going back to this project. Just a heads up, please see https://github.com/ctag-fh-kiel/ctag-tbd/issues/53 where @dromer mentions your  project. Hope some collaboration or contribution will come out of that. Many thanks and keep up the good work.

**Comment by sinneb** [comment]
Thanks for the pointer towards TBD, I'm looking into it now!
